Support non-`SNAPSHOT` Hazelcast versions (#172)
The compatibility tests assume the supplied version is a `SNAPSHOT`:

https://github.com/hazelcast/client-compatibility-suites/blob/8b735bf75002fff2b39f7fb7833c99d78352497e/.github/workflows/server_compatibility.yaml#L666

When it's not, [they
fail](https://github.com/hazelcast/client-compatibility-suites/actions/runs/15880492513)
because the non-`SNAPSHOT` version the earlier stage builds does not
match the `SNAPSHOT` version RC is trying to start:
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:get (default-cli) on project standalone-pom: Couldn't download artifact: The following artifacts could not be resolved: com.hazelcast:hazelcast:jar:tests:5.4.0-SNAPSHOT (absent): Could not find artifact com.hazelcast:hazelcast:jar:tests:5.4.0-SNAPSHOT in temp (https://repository.hazelcast.com/snapshot/)
```

The only caller that required a non-`SNAPSHOT` version was C#:
-
https://github.com/hazelcast/hazelcast-csharp-client/blob/2d6c8dbbff0d72779b495ef8677cb37c4cd0e544/src/Hazelcast.Net.Testing/Conditions/ServerConditionAttribute.cs#L27

 But it appears it supports `SNAPSHOT` versions anyway:
-
https://github.com/hazelcast/hazelcast-csharp-client/blob/2d6c8dbbff0d72779b495ef8677cb37c4cd0e544/src/Hazelcast.Net.Testing/Conditions/ServerConditionAttribute.cs#L77

As such the hardcoded assumption of `SNAPSHOT` can be removed.

Moreover, we don't _need_ the version to be input at all - we can simply
read it from the `pom.xml` of the checked-out Hazelcast codebase.

[Example
execution](https://github.com/hazelcast/client-compatibility-suites/actions/runs/15904884841).