Fix C++ `5.0`/`5.1` build failures [DI-556] (#173)
The compatibility tests [fail for C++
`5.0`/`5.1`](https://github.com/hazelcast/client-compatibility-suites/actions/runs/15851234939):
```HazelcastTests7.cpp:1591:5: error: ‘FIPS_mode_set’ was not declared in this scope```

This is caused by an incompatibility with the older unit test code against OpenSSL `v3`, which was addressed on the C++ client side in https://github.com/hazelcast/hazelcast-cpp-client/pull/1098

The environment obtains OpenSSL as a `gdb` dependency via `apt`, it's version is not static:
https://github.com/hazelcast/client-compatibility-suites/blob/8b735bf75002fff2b39f7fb7833c99d78352497e/.github/workflows/server_compatibility.yaml#L612
```
openssl version
OpenSSL 3.0.13 30 Jan 2024 (Library: OpenSSL 3.0.13 30 Jan 2024)
```

Fixed by disabling the SSL tests in C++ clients <5.2.

[Example execution](https://github.com/hazelcast/client-compatibility-suites/actions/runs/16047218621).

Fixes: [DI-556](https://hazelcast.atlassian.net/browse/DI-556)

[DI-556]: https://hazelcast.atlassian.net/browse/DI-556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ